# Generated by Django 3.2.4 on 2021-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='degree',
            field=models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('D', 'Doctor')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
