# Generated by Django 3.2.4 on 2021-06-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20210628_1825'),
        ('user', '0003_staffinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='faculty.faculty', verbose_name='Факультет'),
        ),
    ]
